### ISSUE TITLE
寻求课程合作

### ISSUE THREAD

**Issue by specialzxw** [bytesc/Image_Recognition_WebGUI#1]
你好，我们是一家线上教育平台，刚刚偶然关注到您的这个项目，想问一下项目是否已经全部完结，若完结了，我们想邀请您结合这个项目在我们平台制作一门线上课程，课程上线后，您每月都可获得不错的收益分成，若您有兴趣尝试，欢迎添加我们的官方合作微信号：shiyanloukecheng，了解合作详情，期待您的联系。

**Comment by bytesc** [comment]
非常高兴您对我的项目感兴趣，我已经通过微信联系，谢谢
