### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by alalert** [bytesc/Image_Recognition_WebGUI#10]
请问下作者你的分类器和训练好的模型是自己弄的吗，还是有参考其他的代码改进的

**Comment by bytesc** [comment]
readme里有写参考文献

**Comment by alalert** [comment]
![image](https://github.com/bytesc/Image_Recognition_WebGUI/assets/156148059/41977711-a0fa-489a-b231-3b2dae19443d)
作者你是移植参考代码里面的框架分类器吗？还是自己手动建立的

**Comment by bytesc** [comment]
复制部分代码，在此基础上有修改
