### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by alalert** [bytesc/Image_Recognition_WebGUI#11]
请问下有没有办法下载下来一部分的数据集，用于测试和训练，作者你发布的基于pywebio和pytorch的诊断课程中，里面代码下载下来后没有数据集和验证机的文件夹
![image](https://github.com/bytesc/Image_Recognition_WebGUI/assets/156148059/1ff63c10-d534-4f05-8d4b-f77183d798eb)

**Comment by bytesc** [comment]
https://github.com/bytesc/lqdata
