### ISSUE TITLE
课程里面的数据失效了，下载不了

### ISSUE THREAD

**Issue by MAIPower** [bytesc/Image_Recognition_WebGUI#14]
课程里面的数据失效了，下载不了

**Comment by bytesc** [comment]
https://github.com/bytesc/lqdata
您好，是这个吗？
如果方便，请给出错误截图。
@MAIPower

**Comment by MAIPower** [comment]
是的，教程里面的连接访问不了，直接超时了，感谢回复



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月16日(星期二) 下午2:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [bytesc/Image_Recognition_WebGUI] 课程里面的数据失效了，下载不了 (Issue #14)














 
https://github.com/bytesc/lqdata
 您好，是这个吗？
 如果方便，请给出错误截图。
 @MAIPower

**Comment by bytesc** [comment]
这是因为国内网络环境的原因，可以使用代理等方法解决。
也可以试试以下替代。
https://gitee.com/bytesc/lqdata
@MAIPower
