### ISSUE TITLE
模型未能正常识别

### ISSUE THREAD

**Issue by NikolaZY0727** [bytesc/Image_Recognition_WebGUI#15]
我使用自己的.nii图像上传之后会显示模型识别错误，可能是服务器空间不足这么一句话
![IMG_0488](https://github.com/bytesc/Image_Recognition_WebGUI/assets/169753107/96be0dc5-d675-47eb-b82f-ebbb62a2569b)

**Comment by bytesc** [comment]
应该是上传的图像格式不对。

**Comment by NikolaZY0727** [comment]
好的感谢回复&nbsp;


赵芫
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月18日(星期六) 晚上7:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [bytesc/Image_Recognition_WebGUI] 模型未能正常识别 (Issue #15)














 
应该是上传的图像格式不对。
