### ISSUE TITLE
macOS渲染图片时程序崩溃

### ISSUE THREAD

**Issue by zjgxcj** [bytesc/Image_Recognition_WebGUI#16]
根据崩溃报告,程序在创建NSWindow对象时发生了异常并崩溃。主要问题出在以下代码:
-[NSWindow _initContent:styleMask:backing:defer:contentView:]
这通常是由于尝试在非主线程上创建或操作UI元素导致的。在macOS中,所有UI相关操作都必须在主线程上执行。
要解决这个问题,您需要确保所有涉及NSWindow或其他UI元素的代码都在主线程上运行。

**Comment by bytesc** [comment]
您好，项目只在 windows 和 ubuntu 平台上进行过测试，没有使用过 macOS。不过此项目一个不涉及到操作系统 UI。
