### ISSUE TITLE
上传.nii文件失败

### ISSUE THREAD

**Issue by alalert** [bytesc/Image_Recognition_WebGUI#4]
![Uploading 1705742861976.jpg…]()

**Comment by bytesc** [comment]
你是在自己电脑上本地运行吗?

**Comment by alalert** [comment]
是的

**Comment by bytesc** [comment]
请你给出控制台输出的报错信息，和具体上传的.nii文件是哪一个。

**Comment by alalert** [comment]
显示报错为：’‘输入错误，请上传医学影像文件(.nii)’‘，每一个test文件都不行，且图像渲染十几二十分钟也没反应，不知道是不是正常现象

**Comment by alalert** [comment]
代码运行刚刚报了个错误： UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
  plt.imshow(img[:, :, layer], cmap='gray')

**Comment by bytesc** [comment]
截图(完整)

**Comment by bytesc** [comment]
这种情况大概率是环境没配好。或者没有严格按照readme文档中的指南运行。

**Comment by alalert** [comment]
![image](https://github.com/bytesc/Image_Recognition_WebGUI/assets/156148059/b38614c0-7235-4bc4-8fca-ff830a41b66b)
![image](https://github.com/bytesc/Image_Recognition_WebGUI/assets/156148059/b0cce30c-a937-4c4d-a32e-a78abce3f679)

截图显示是上面这个地址

**Comment by alalert** [comment]
![image](https://github.com/bytesc/Image_Recognition_WebGUI/assets/156148059/6b4cf1cf-21ad-48b4-9512-91041d458851)

**Comment by alalert** [comment]
请问博主这个项目有相关的论文吗？

**Comment by bytesc** [comment]
论文readme里有写。
截图(完整)，是指控制台输出的报错信息截图

**Comment by alalert** [comment]
![image](https://github.com/bytesc/Image_Recognition_WebGUI/assets/156148059/126464ad-9227-4b33-a7b5-bf82326f2b2e)


D:\software\python\Image_Recognition_WebGUI-1.0.0\Image_Recognition_WebGUI-1.0.0\venv\Scripts\python.exe D:\software\python\Image_Recognition_WebGUI-1.0.0\Image_Recognition_WebGUI-1.0.0\demo01.py 
Running on all addresses.
Use http://192.168.1.8:6006/ to access the application
D:\software\python\Image_Recognition_WebGUI-1.0.0\Image_Recognition_WebGUI-1.0.0\hot_img.py:38: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
  plt.imshow(img[:, :, layer], cmap='gray')

**Comment by bytesc** [comment]
<img width="676" alt="Snipaste_2024-01-20_19-35-57" src="https://github.com/bytesc/Image_Recognition_WebGUI/assets/103081365/d4ecd7db-0c9b-42f9-ae9c-41215adf65e0">
依赖安装问题。

**Comment by bytesc** [comment]
complete
