### ISSUE TITLE
上传图像失败

### ISSUE THREAD

**Issue by alalert** [bytesc/Image_Recognition_WebGUI#5]
各种环境已经按照requirement安装好了（tqdm库我是下载的 4.66.1版本），仍无法解决图像上传问题，
![image](https://github.com/bytesc/Image_Recognition_WebGUI/assets/156148059/68492b11-fc05-45b2-8729-3fc5bec3c483)

**Comment by bytesc** [comment]
1, 你上传的 `.nii` 图像在我部署的线上环境和你本地是否都上传失败。
2, 如果是你本地环境报错，请给出具体的报错信息。

**Comment by alalert** [comment]
我通过debug查找，发现在 with open(temp_file_path, 'wb') as file: 这一句报错跳入到except异常处理，然后refresh（）又进入代码开始处，所以一直没办法进入到后续识别分类中




&nbsp; &nbsp; &nbsp; &nbsp; if is_demo is False:&nbsp; &nbsp;#上传.nii图像
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; try:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; inpic = pywebio.input.file_upload(label="上传医学影像(.nii)")
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; inpic = BytesIO(inpic['content'])


&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; temp_file_path = "./nii/" + generate_random_str() + ".nii"&nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; with open(temp_file_path, 'wb') as file:&nbsp; &nbsp; &nbsp; #此句运行后跳到except中了
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; file.write(inpic.getvalue())&nbsp; # 保存到本地
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; print_logs("upload_file," + temp_file_path + ",\n", user_ip)&nbsp;&nbsp;


&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; except :&nbsp; &nbsp;&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; pywebio.output.toast("输入错误，请上传医学影像文件(.nii)", color="warn")
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; refresh()





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bytesc/Image_Recognition_WebGUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月21日(星期三) 下午5:00
***@***.***&gt;;
抄送:&nbsp;"20级通信工程 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [bytesc/Image_Recognition_WebGUI] 上传图像失败 (Issue #5)





 
1, 你上传的 .nii 图像在我部署的线上环境和你本地是否都上传失败。
 2, 如果是你本地环境报错，请给出具体的报错信息。

**Comment by bytesc** [comment]
你的路径下是否存在，`./nii/`这个文件夹，没有就新建一个空的。
