### ISSUE TITLE
续

### ISSUE THREAD

**Issue by alalert** [bytesc/Image_Recognition_WebGUI#6]
请问你部署的线上环境是如何操作的呢

**Comment by alalert** [comment]
![image](https://github.com/bytesc/Image_Recognition_WebGUI/assets/156148059/2d66e271-3cbd-4c47-8e3f-048d3cbc2f4e)
我通过debug查找，发现在  with open(temp_file_path, 'wb') as file:    这一句报错跳入到except异常处理，然后refresh（）又进入代码开始处，所以一直没办法进入到后续识别分类中
![image](https://github.com/bytesc/Image_Recognition_WebGUI/assets/156148059/5c34f9f6-1158-4673-9e35-f3a69647df7e)

**Comment by alalert** [comment]
if is_demo is False:   #上传.nii图像
                try:
                    inpic = pywebio.input.file_upload(label="上传医学影像(.nii)")
                    inpic = BytesIO(inpic['content'])

                    temp_file_path = "./nii/" + generate_random_str() + ".nii"   
                    with open(temp_file_path, 'wb') as file:      #此句运行后跳到except中了
                        file.write(inpic.getvalue())  # 保存到本地
                    print_logs("upload_file," + temp_file_path + ",\n", user_ip)  

                except :    
                    pywebio.output.toast("输入错误，请上传医学影像文件(.nii)", color="warn")
                    refresh()

**Comment by bytesc** [comment]
你的路径下是否存在，./nii/这个文件夹，没有就新建一个空的。由于git会忽略空文件夹，所以你clone下来可能要手动新建。

**Comment by alalert** [comment]
好的 问题解决了 谢谢
